Repository games647/FastLogin, pull requests merged in 2021-05, with the labels that each got.

#525 Fix Floodgate 2.0 on BungeeCord
  bungee/pom.xml
  bungee/src/main/java/com/github/games647/fastlogin/bungee/FastLoginBungee.java
  bungee/src/main/java/com/github/games647/fastlogin/bungee/listener/ConnectListener.java
Labels: bug

#527 Implement floodgate api version 2.0
  bungee/src/main/java/com/github/games647/fastlogin/bungee/hook/floodgate/FloodgateHook.java
  bungee/src/main/java/com/github/games647/fastlogin/bungee/hook/floodgate/FloodgateV1Hook.java
  bungee/src/main/java/com/github/games647/fastlogin/bungee/hook/floodgate/FloodgateV2Hook.java
  bungee/src/main/java/com/github/games647/fastlogin/bungee/listener/ConnectListener.java
Labels: enhancement

#528 Actually assign the queried version to a variable
  bungee/src/main/java/com/github/games647/fastlogin/bungee/FastLoginBungee.java
Labels: bug

#530 Change dependency Floodgate Bungee to API
  bungee/pom.xml
Labels: BungeeCord, enhancement

#494 Floodgate support for Bukkit
  .gitignore
  bukkit/pom.xml
  bukkit/src/main/java/com/github/games647/fastlogin/bukkit/FastLoginBukkit.java
  bukkit/src/main/java/com/github/games647/fastlogin/bukkit/listener/ConnectionListener.java
  bukkit/src/main/java/com/github/games647/fastlogin/bukkit/listener/protocollib/NameCheckTask.java
  bukkit/src/main/java/com/github/games647/fastlogin/bukkit/listener/protocolsupport/ProtocolSupportListener.java
  bukkit/src/main/java/com/github/games647/fastlogin/bukkit/task/FloodgateAuthTask.java
  bukkit/src/main/resources/plugin.yml
  core/src/main/resources/config.yml
Labels: enhancement

#534 Warn in config: linked players conflict their Java name
  core/src/main/resources/config.yml
Labels: enhancement
